### ISSUE TITLE
Valid License Not Found

### ISSUE THREAD

**Issue by NormanFPC** [NextronSystems/aurora-agent-manual#4] opened 2023-05-20 16:08 UTC
I put the license into the extracted folder.

I get the error message valid license not present after the installer tells me the license file was found.

There seems to be a bug in it not reading the license file in the folder or where in the folder should the license file be placed?

All the manual says is to put it in the folder, which I did.

I tried to install Aurora Lite with the Dashboard. No joy!

**Comment by redteampanda-ng** [comment] 2023-05-20 18:11
Thanks for reaching out to us.

I was able to just reproduce the same problem with a fresh copy of Aurora Lite + license. I escalated this internally and will get back to you once this is fixed.

Regarding the license, it is enough to place this in the root directory of your Aurora Lite.

**Comment by NormanFPC** [comment] 2023-05-20 18:59
That's what I did with the license added to the root directory.

For some reason, the installer does locate it but then reports a valid
license not present.

When you do have a fix, let me know. Thanks for your fast response on the
issue.

Norman F Birnberg

**Comment by redteampanda-ng** [comment] 2023-05-22 08:55
Hi Norman,

the issue was fixed just now. You should receive an email with a notification that your aurora lite license will expire in 7 days. This is related to your issue, the license which was generated for you was incorrect. Please download the new license and try again.

Please close this issue if aurora lite works now. If you have any other questions or issues, feel free to ask.

**Comment by NormanFPC** [comment] 2023-05-22 12:29
I tried it again with the new license. Don't know why the installer isn't acknowledging it.

Still keep getting this error message:

could not install aurora agent: startup error: no valid license present

**Comment by redteampanda-ng** [comment] 2023-05-22 12:45
Hi Norman,

this works for me since we applied the update today. What OS are you trying to install Aurora on?
Alternatively, you could open a ticket with the e-mail you used to register for aurora. This way I could have a look what your license looks like. Just send us an email to support@ and I will look into it.

![image](https://github.com/NextronSystems/aurora-agent-manual/assets/31235211/08f35090-3e2c-4ced-bb24-cc0786ec5586)

**Comment by NormanFPC** [comment] 2023-05-22 13:10
Hi, 

I've installed it on Windows 11 22H2.

It worked for you and since this platform doesn't support it directly, I'm sending the license and a screenshot illustrating the Aurora Agent installer output to you in a zip file. May you might be able to figure out why my installer isn't listing the parameters when starting the Aurora Agent service as you showed in your screenshot.

**Comment by redteampanda-ng** [comment] 2023-05-22 14:13
Hi Norman,

thank you for the zip file. I contacted github and the file has been deleted. Please do not upload license files here directly, they contain your e-mail address.

I will look into Windows 11 22h2 and let you know if and when the issue will be fixed.

I will keep you updated.

**Comment by NormanFPC** [comment] 2023-05-22 17:33
That sucks because I thought the license had only the embedded license number which wouldn't violate any rules. Didn't know.

I thought you might need to check it as you had requested.

Its strange because at the core, Windows 11 is still Windows 10. Who knows thought what changes Microsoft made in the last two builds.

I'll await further news. Thanks for your help!

**Comment by redteampanda-ng** [comment] 2023-05-23 06:09
Hi Norman,

I just installed a fresh Windows 11 22H2, installed all updates and didn't change anything on the system. Aurora Lite works for me:
![image](https://github.com/NextronSystems/aurora-agent-manual/assets/31235211/36924255-3850-4078-bd87-abf582898214)

I also tried to install it with your license and it works as well.
You could try to start aurora without installing it and running the "--debug" flag:

``aurora-agent-64.exe --debug``

This will give you a lot of output, but perhaps we can see more information regarding why the license does not work (towards the end you should see infos about the license). You could also download a fresh copy of aurora lite and see if this helps.

Edit: You can also send us the screenshot of the normal installation you are trying and the debugging output in .txt format to our support e-mail address. This would help us to debug this quicker: support[at]nextron-systems.com

**Closed as not planned** 2023-06-20 12:14 UTC
